sudo: false
language: java
jdk: oraclejdk8

addons:
  apt:
    packages:
      - xvfb
  sonarcloud:
    organization: "collonville-tom-github"
    token:
      secure: "748b7fca9a6fbfe5072f997a232f5c4e0ca0e6ca"

before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
  - sleep 3 # give xvfb some time to start
before_install:
  - "/sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x16"
install: true
before_script : true



script: 
  - cp .travis.settings.xml $HOME/.m2/settings.xml 
  - mvn install deploy
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'




