sudo: false
language: java
jdk: oraclejdk8

addons:
  apt:
    packages:
      - xvfb
  sonarcloud:
    organization: "collonville-tom-github"
    token:
      secure: "748b7fca9a6fbfe5072f997a232f5c4e0ca0e6ca"

before_script : true
install:
  - export DISPLAY=':99.0'
  - Xvfb :99 -screen 0 1024x768x24 > /dev/null 2>&1 &
before_script : true


script: 
  - cp .travis.settings.xml $HOME/.m2/settings.xml 
  - mvn install 
  - mvn clean org.jacoco:jacoco-maven-plugin:prepare-agent package sonar:sonar -Dsonar.host.url=https://sonarcloud.io

cache:
  directories:
    - '$HOME/.m2/repository'
    - '$HOME/.sonar/cache'




